# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/mygit/new_CG/new_cg/new_cg.srcs/sources_1/ip/float_mult/float_mult.xci
# IP: The module: 'float_mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/mygit/new_CG/new_cg/new_cg.srcs/sources_1/ip/float_mult/float_mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float_mult'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/mygit/new_CG/new_cg/new_cg.srcs/sources_1/ip/float_mult/float_mult.xci
# IP: The module: 'float_mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/mygit/new_CG/new_cg/new_cg.srcs/sources_1/ip/float_mult/float_mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float_mult'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
